Product launch page
TheGarvel/Garvel pull request #102
Opened 2022-05-24 03:40 UTC by yamap19950521

## 產品上架頁面切版

<img width="565" alt="截圖 2022-05-24 上午12 11 32" src="https://user-images.githubusercontent.com/96513629/169942745-014ae1d4-f8f5-41e1-8595-2ba6eb51fc33.png">
<img width="559" alt="截圖 2022-05-24 上午12 11 20" src="https://user-images.githubusercontent.com/96513629/169942735-7bae9422-3c04-4c5e-b3f4-e22fd90149d7.png">
<img width="1281" alt="截圖 2022-05-24 上午12 10 32" src="https://user-images.githubusercontent.com/96513629/169942701-030af873-6a1b-47ce-b779-844892fe925d.png">
<img width="1276" alt="截圖 2022-05-24 上午12 11 01" src="https://user-images.githubusercontent.com/96513629/169942722-2cc9ded1-8bef-4c64-be58-859fef32c37e.png">
<img width="1175" alt="截圖 2022-05-24 上午11 29 12" src="https://user-images.githubusercontent.com/96513629/169943692-cbc02785-4c43-48dc-bb48-f751bcbf270c.png">

2022-05-24 11:24 UTC, ChenKLi requested changes

2022-05-24 11:24 UTC, ChenKLi commented on app/views/products/_form.html.erb
> +            <%= form.label :start_price, "起標價格：", class:"text-gray-800"%>
這邊的 class 少一個 s ，另外這邊多包一個 div 感覺有點多餘

2022-05-24 11:43 UTC, yamap19950521 commented on app/views/products/_form.html.erb
> +            <%= form.label :start_price, "起標價格：", class:"text-gray-800"%>
好的，謝謝提醒

2022-05-25 15:00 UTC, ChenKLi approved these changes

2022-05-26 08:00 UTC, Weian0328 approved these changes

2022-05-29 06:34 UTC, cin-yi-wei approved these changes

2022-05-29 06:35 UTC, merged

2022-05-29 06:35 UTC, zoechaoweiting approved these changes