make infinite scrolling with IntersectionObserver
TheGarvel/Garvel pull request #135
Opened 2022-06-03 14:03 UTC by cin-yi-wei

#133 
加入無限滾輪，滑到底部時，自動ajax下一頁，把資料使用useState更新產品陣列

![Gavel 00_00_00-00_00_30](https://user-images.githubusercontent.com/12572986/171866378-4603a8e5-8b87-483a-ac84-bdbcc7aeb684.gif)

2022-06-05 11:05 UTC, ChenKLi requested changes
測試 seed 檔無限下拉捲軸讀取時無異常，想問這裡的 loading 和 error 字樣會再做設計嗎？

2022-06-06 12:53 UTC, ChenKLi approved these changes

2022-06-06 12:53 UTC, Weian0328 approved these changes

2022-06-06 13:04 UTC, yamap19950521 approved these changes

2022-06-06 13:05 UTC, merged