Add service form
TheGarvel/Garvel pull request #66
Opened 2022-04-26 10:48 UTC by Weian0328

客服表單畫面

<img width="601" alt="截圖 2022-04-26 下午6 47 22" src="https://user-images.githubusercontent.com/100757017/165283758-ffb6ccab-6bf4-4f98-ad95-55cc54a6c2c9.png">

2022-04-26 11:03 UTC, ChenKLi requested changes
users/index.html.erb 中測試tailwind的部分記得移除

2022-04-26 11:07 UTC, Weian0328 commented
> users/index.html.erb 中測試tailwind的部分記得移除

已移除～～

2022-04-27 08:41 UTC, ChenKLi approved these changes
已確認OK

2022-04-27 09:08 UTC, zzr1226sdo approved these changes

2022-04-27 14:31 UTC, cin-yi-wei approved these changes
check ok

2022-04-29 08:59 UTC, cin-yi-wei commented
目前有衝突無法合併

2022-04-30 09:03 UTC, merged