Tailwind product report page
TheGarvel/Garvel pull request #67
Opened 2022-04-27 09:13 UTC by zzr1226sdo

<img width="799" alt="Screen Shot 2022-04-27 at 5 13 07 PM" src="https://user-images.githubusercontent.com/43497901/165484812-c52104ba-522f-4b4b-bbb3-31c223927537.png">

請幫看

2022-04-27 10:28 UTC, ChenKLi requested changes
1. 使用上流程填完後應該可以直接提交，而不是移到右側去按，建議下方button的位子可以改到左側，應該有個text-right可以改成text-left，然後因為那個區塊本身有padding，建議上方區塊也增加padding的距離去切齊下方的button的位置，讓畫面看起來比較一致。
2. button的「save」可以改成「提交」或「送出」
3. 感覺button 區塊的顏色可以跟背景一樣是白色就好，那個div特別設置灰色感覺怪怪的

2022-04-27 14:36 UTC, zzr1226sdo commented
> 1. 使用上流程填完後應該可以直接提交，而不是移到右側去按，建議下方button的位子可以改到左側，應該有個text-right可以改成text-left，然後因為那個區塊本身有padding，建議上方區塊也增加padding的距離去切齊下方的button的位置，讓畫面看起來比較一致。
> 2. button的「save」可以改成「提交」或「送出」
> 3. 感覺button 區塊的顏色可以跟背景一樣是白色就好，那個div特別設置灰色感覺怪怪的

收到，我改一下

2022-04-28 03:43 UTC, Weian0328 commented
現在畫面長這樣我個人的想法是送出的按鈕在右邊比較正常,不知道其他人有什麼想法





<img width="601" alt="截圖 2022-04-28 上午11 40 14" src="https://user-images.githubusercontent.com/100757017/165671711-145dc697-886f-42fa-a274-444d5b4e634a.png">

2022-04-28 04:07 UTC, ChenKLi commented
> 現在畫面長這樣我個人的想法是送出的按鈕在右邊比較正常,不知道其他人有什麼想法
> 
> <img alt="截圖 2022-04-28 上午11 40 14" width="601" src="https://user-images.githubusercontent.com/100757017/165671711-145dc697-886f-42fa-a274-444d5b4e634a.png">

其實左右都有，但因為畫面太寬了滑鼠移了很遠，所以才會想說移到左邊。如果要切到右邊的話，我的想法是把這個表單的樣式也做成客服表單那樣居中的區塊，這種就會比較是平常我們看到的那種button在右邊的版型。但也有可能是我網站看得不夠多，所以如果大家有共識的話，左邊右邊我覺得都OK。

2022-04-28 04:08 UTC, ChenKLi approved these changes
check OK

2022-04-28 04:37 UTC, Weian0328 approved these changes
ok~

2022-04-28 05:29 UTC, zzr1226sdo commented
我都可以 大家ok我就ok

2022-04-28 15:33 UTC, yamap19950521 approved these changes

2022-04-29 08:58 UTC, cin-yi-wei commented
目前有衝突無法合併

2022-04-29 17:39 UTC, merged

2022-04-29 17:39 UTC, zzr1226sdo commented
> 目前有衝突無法合併

靠北 我以為點merge可以看到衝突.. 這樣好像合進去了