Combine user product
TheGarvel/Garvel pull request #81
Opened 2022-05-09 08:49 UTC by cin-yi-wei

1. 使用賣家的角度去建立商品，產品只屬於一個賣家，一個賣家可以有多個產品
2. 在product show頁面只會顯示自己所有的商品。
![image](https://user-images.githubusercontent.com/12572986/167370918-51e10a6d-1df3-4ac1-bd94-7ac2c9655156.png)

3. 只有賣家身分(要通過email驗證、sms驗證)才能訪問我的賣場頁面，否則被轉址到手機驗證頁面
4. 新增註冊手機頁面，使用簡訊發送平台發送簡訊到使用者手機上
5. 新增手機驗證碼頁面，將使用者之驗證碼交給平台驗證，驗證碼一致將返回approved
![Garvel](https://user-images.githubusercontent.com/12572986/167374502-c3c46de4-bae1-4cdc-9675-5ceb942b8248.gif)

2022-05-09 10:24 UTC, ChenKLi requested changes

2022-05-09 10:24 UTC, ChenKLi commented on config/initializers/authy.rb
> +# VAbd032ca6a38e447594f389f108b4a45f
沒用到的檔案記得刪掉

2022-05-09 16:56 UTC, ChenKLi approved these changes

2022-05-10 09:10 UTC, Weian0328 approved these changes

2022-05-11 07:43 UTC, zzr1226sdo approved these changes

2022-05-11 11:02 UTC, merged