sign_up updata  and validates
TheGarvel/Garvel pull request #85
Opened 2022-05-15 07:55 UTC by yamap19950521

2022-05-15 12:01 UTC, ChenKLi requested changes

2022-05-15 12:01 UTC, ChenKLi commented on app/models/user.rb
> +  validates :username, uniqueness: true, presence: true
一樣的條件的設置可以整合在一起，可以不用拆開哦。
``` ruby
validates :email, :username, uniqueness: true, presence: true
```

2022-05-17 02:39 UTC, cin-yi-wei commented on postcss.config.js
> -    require("tailwindcss")("app/javascript/css/tailwind.js"),
`("app/javascript/css/tailwind.js")`
要留著 ，不然tailwind有些東西會壞掉

2022-05-17 03:13 UTC, cin-yi-wei approved these changes
check ok

2022-05-17 06:10 UTC, Weian0328 approved these changes
ok~

2022-05-17 12:43 UTC, ChenKLi approved these changes

2022-05-17 12:47 UTC, merged