add_search and navbar
TheGarvel/Garvel pull request #88
Opened 2022-05-17 07:08 UTC by yamap19950521

1.使用elaeticsearch 及 searchkick完成模糊搜尋(透過ajax不離開目前的頁面)
模糊搜尋相關設定(暫定以後都可以更改)：
(1)	可以使索引與數據庫保持同步
           callbacks: :async

(2)部分匹對
目前使用單詞(word_middle)的任何部分匹對
我覺得網購比較適合word_middle（例如：ppl匹配到apple）或text_middle(een app匹配到green apple)	
word_middle: [:name]

(3) 可搜索字段
目前設定只有商品name可搜索
searchable: [:name]

(4) 拼寫錯誤 
預設編輯距離為1，我改成2
misspellings: {edit_distance: 2}

也可以使用（如果結果少於 5 個，則啟用拼寫錯誤的情況下執行第二次搜索。返回此查詢的結果。）
	Product.search("zuchini", misspellings: {below: 5})

ps： 搜尋的autocomplete我沒做 之後有空擋再研究

2.navbar切版

<img width="1439" alt="截圖 2022-05-17 下午3 00 43" src="https://user-images.githubusercontent.com/96513629/168749975-caa27338-443f-4332-975a-da4e5978923e.png">
<img width="1440" alt="截圖 2022-05-17 下午3 03 16" src="https://user-images.githubusercontent.com/96513629/168749988-40646b7e-af33-4cfe-887c-0b5ee9a44dca.png">
<img width="497" alt="截圖 2022-05-17 下午3 03 25" src="https://user-images.githubusercontent.com/96513629/168749993-f3a7695f-3d32-450c-83cb-d21f996f134b.png">
<img width="1435" alt="截圖 2022-05-17 下午3 03 40" src="https://user-images.githubusercontent.com/96513629/168749998-4661e708-45d2-42d3-b700-d912bd77a9da.png">
<img width="495" alt="截圖 2022-05-17 下午3 03 50" src="https://user-images.githubusercontent.com/96513629/168750004-5bba4e85-fe25-414f-81ae-6fc1553b8878.png">

2022-05-17 10:51 UTC, zzr1226sdo commented
測試ok

2022-05-17 12:42 UTC, ChenKLi commented
衝突可以先解哦

2022-05-18 04:34 UTC, ChenKLi requested changes

2022-05-18 04:34 UTC, ChenKLi commented on app/javascript/controllers/search_controller.js
> +
空行可以刪掉

2022-05-18 04:34 UTC, ChenKLi commented on app/javascript/css/product.css
> +
空行可以刪掉

2022-05-18 04:34 UTC, ChenKLi commented on app/views/layouts/application.html.erb
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
這兩行meta的內容感覺是一樣的東西，可以整合成一行就好

2022-05-18 04:34 UTC, ChenKLi commented on app/views/layouts/product.html.erb
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
這邊的meta感覺是一樣的東西，看要不要整合成一行

2022-05-18 04:34 UTC, ChenKLi commented on app/views/layouts/user.html.erb
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
這個內容跟application.html.erb一樣，感覺不需要在user另外layout這個頁面

2022-05-18 05:08 UTC, cin-yi-wei commented on app/views/layouts/product.html.erb
> +        </div>
navbar 可以移到application.html.erb

2022-05-18 05:52 UTC, cin-yi-wei commented
資料庫 schema 有變
rails db:drop
rails db:create
rails db:migrate
去改變schema 
再推上來一次

2022-05-18 06:09 UTC, yamap19950521 commented
> 資料庫 schema 有變 rails db:drop rails db:create rails db:migrate 去改變schema 再推上來一次

已修正

2022-05-18 07:37 UTC, ChenKLi approved these changes

2022-05-19 08:17 UTC, zzr1226sdo approved these changes

2022-05-19 09:09 UTC, Weian0328 approved these changes

2022-05-19 09:44 UTC, zoechaoweiting approved these changes
測試ok

2022-05-19 13:00 UTC, merged