Feature/tag
TheGarvel/Garvel pull request #91
Opened 2022-05-17 13:16 UTC by zoechaoweiting

1. add tag & products_tag model and controller
2. create many-to-many relationship between tag & product
3. 建立 tag 的 seeds，測試前須先執行`rails db:seed`。
4. 在新增 product 的頁面中加入選擇 tag 的欄位，每選定一個 tag 時，會動態產生下一個 tag 選單，最多三層。
![Tab-1652789569551](https://user-images.githubusercontent.com/100757402/168817023-0bc5b7a1-b304-4995-923a-f77dfe38ebb8.gif)
5. 建立個別 tag 底下所有 products 的 api，並轉成 json 格式。
![截圖 2022-05-17 下午8 19 13](https://user-images.githubusercontent.com/100757402/168817236-671f2d2a-3f39-44ef-842e-36eba9dc424d.png)
![截圖 2022-05-17 下午8 19 26](https://user-images.githubusercontent.com/100757402/168817259-48866dca-c92d-4e72-acd4-707675be8293.png)

2022-05-17 16:02 UTC, cin-yi-wei commented on app/assets/stylesheets/api/v1/tags.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
沒用到可以刪掉

2022-05-17 16:02 UTC, cin-yi-wei commented on app/helpers/api/v1/tags_helper.rb
> +end
沒用到可以刪掉

2022-05-17 16:02 UTC, cin-yi-wei commented on app/views/products/index.html.erb
> +<%= link_to "Create product" , new_product_path ,class: "hover:text-indigo-600"%>
上面都可以刪掉了
這個頁面已經被移動到own.html.erb了

2022-05-17 16:02 UTC, cin-yi-wei commented on app/views/products/own.html.erb
> +      <% product.tags.each do |tag| %>
感覺這邊不用顯示tag
不然自己的產品  後面有一排tag
show頁面在顯示出來就好了

2022-05-17 16:02 UTC, cin-yi-wei commented on config/routes.rb
> +      get :tag
這兩條路徑有用到嗎?
因為我們類別是手動新增(seed)

2022-05-17 16:02 UTC, cin-yi-wei commented on test/controllers/api/v1/tags_controller_test.rb
> +end
沒有用的可以拿掉

2022-05-17 16:02 UTC, cin-yi-wei commented on test/fixtures/products_tags.yml
> +  tag: two
沒有用的可以拿掉

2022-05-17 16:02 UTC, cin-yi-wei commented on test/fixtures/tags.yml
> +  name: MyString
沒有用的可以拿掉

2022-05-17 16:02 UTC, cin-yi-wei commented on test/models/products_tag_test.rb
> +end
沒有用的可以拿掉

2022-05-17 16:02 UTC, cin-yi-wei commented on test/models/tag_test.rb
> +end
沒有用的可以拿掉

2022-05-17 17:15 UTC, ChenKLi requested changes
一些小地方修改

2022-05-17 17:15 UTC, ChenKLi commented on app/controllers/api/v1/categories_controller.rb
> +    # render html: params
之前測試的內容也可以刪掉哦

2022-05-17 17:15 UTC, ChenKLi commented on app/controllers/products_controller.rb
> +    # debugger
這看起來也是之前用dubugger的部分

2022-05-17 17:15 UTC, ChenKLi commented on config/routes.rb
> +
多餘的空行

2022-05-18 06:23 UTC, zoechaoweiting reviewed
以上修正完成
1. 移除多餘的檔案
2. 調整 index.html.erb & own.html.erb
3. 刪除之前測試的code跟routes

2022-05-19 06:44 UTC, ChenKLi requested changes

2022-05-19 06:44 UTC, ChenKLi commented on app/javascript/controllers/tag_controller.js
> +    console.log(123);
這個console.log應該也是不要的

2022-05-19 06:44 UTC, ChenKLi commented on input.html
> +```
看起來是多餘的檔案

2022-05-19 08:21 UTC, ChenKLi commented on app/javascript/controllers/tag_controller.js
> +    console.log(123);
input.html確認有刪掉了，這段記得也要修正哦

2022-05-19 08:47 UTC, zoechaoweiting commented on app/javascript/controllers/tag_controller.js
> +    console.log(123);
已修正感謝～

2022-05-21 05:26 UTC, cin-yi-wei approved these changes
check ok

2022-05-21 05:51 UTC, ChenKLi approved these changes

2022-05-21 06:12 UTC, Weian0328 approved these changes

2022-05-21 08:50 UTC, merged