Product launch page
TheGarvel/Garvel pull request #92
Opened 2022-05-18 09:26 UTC by yamap19950521

# 切版-商品上架頁面

<img width="1434" alt="截圖 2022-05-18 下午5 22 49" src="https://user-images.githubusercontent.com/96513629/169005788-1669c6ba-c2ff-49ad-ae53-5bec3c6f9fb2.png">
<img width="1437" alt="截圖 2022-05-18 下午5 22 56" src="https://user-images.githubusercontent.com/96513629/169005804-849fbf18-ea64-4bef-b1a2-0b1e012f4378.png">
<img width="485" alt="截圖 2022-05-18 下午5 23 13" src="https://user-images.githubusercontent.com/96513629/169005812-b293cac5-d7ac-4e72-8e62-ee9dedd2a25e.png">
<img width="484" alt="截圖 2022-05-18 下午5 23 28" src="https://user-images.githubusercontent.com/96513629/169005819-7642741a-9318-4d10-93c6-1a362dc65dc2.png">

2022-05-19 08:17 UTC, ChenKLi requested changes

2022-05-19 08:17 UTC, ChenKLi commented on app/views/products/_form.html.erb
> +      </div>
這邊的「X」 跟右側的「取消」是不是一樣的功能，如果是的話我覺得保留取消就好

2022-05-19 08:17 UTC, ChenKLi commented on app/views/products/_form.html.erb
> +        <%= form_for( product, html:  {enctype: "multipart/form-data"}) do |form|%>
```
 html:  {enctype: "multipart/form-data"})
 ```
 想知道這段是什麼意思

2022-05-19 08:35 UTC, yamap19950521 commented on app/views/products/_form.html.erb
> +      </div>
好的，那我保留取消就好

2022-05-19 08:35 UTC, yamap19950521 commented on app/views/products/_form.html.erb
> +        <%= form_for( product, html:  {enctype: "multipart/form-data"}) do |form|%>
這段不是我寫，你可以參考Add room model and make relationship的PR ，好像是做驗證的

2022-05-19 08:46 UTC, yamap19950521 commented on app/views/products/_form.html.erb
> +      </div>
已修正囉

2022-05-21 06:30 UTC, ChenKLi requested changes

2022-05-21 06:30 UTC, ChenKLi commented on app/javascript/css/product.css
> +
這段結尾少一個大括號

2022-05-21 06:47 UTC, ChenKLi requested changes

2022-05-21 06:47 UTC, ChenKLi commented on app/views/products/_form.html.erb
> +        <%= form.submit "立即刊登", class:"bg-blue-600 text-white hover:bg-blue-700 rounded p-2 py-3 mx-2 text-sm border border-blue-800"%>
這邊的立即刊登好像實際上沒有送出任何資訊，按下去的時候會因為得到一個空值跳錯誤。
小小的建議，看要不要把最上面那行拿掉，然後在下方「立即刊登」附近做一個「返回」按鈕就好，按鈕看要並列左右放還是上下排列都可以

2022-05-21 11:01 UTC, yamap19950521 commented on app/javascript/css/product.css
> +
sorry沒注意到，謝謝提醒。

2022-05-21 11:32 UTC, yamap19950521 commented on app/views/products/_form.html.erb
> +        <%= form.submit "立即刊登", class:"bg-blue-600 text-white hover:bg-blue-700 rounded p-2 py-3 mx-2 text-sm border border-blue-800"%>
已修正囉

2022-05-22 11:06 UTC, ChenKLi commented
postcss後面讀取("app/javascript/css/tailwind.js")這段記得補上應該就沒問題了

2022-05-22 11:08 UTC, ChenKLi requested changes

2022-05-22 11:08 UTC, ChenKLi commented on postcss.config.js
>      require("postcss-flexbugs-fixes"),
postcss 後面讀取("app/javascript/css/tailwind.js")這段記得補上應該就沒問題了

2022-05-22 12:29 UTC, Weian0328 approved these changes

2022-05-22 14:43 UTC, ChenKLi approved these changes

2022-05-22 14:48 UTC, closed without merging