add autocomplete & search api
TheGarvel/Garvel pull request #96
Opened 2022-05-20 15:47 UTC by yamap19950521

1. 使用 stimulus-autocomplete 製作搜尋autocomplete
2. 使用will_paginate 製作分頁的api，之後翊瑋會以前端的角色去把資料呈現在畫面上。
3. 
<img width="1435" alt="截圖 2022-05-20 下午11 29 02" src="https://user-images.githubusercontent.com/96513629/169564798-7be825c8-6d79-4b56-8179-81a7deae3846.png">

2022-05-21 06:17 UTC, ChenKLi requested changes

2022-05-21 06:17 UTC, ChenKLi commented on app/assets/stylesheets/api/v1/products.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
沒有用到的檔案可以砍掉

2022-05-21 06:17 UTC, ChenKLi commented on app/assets/stylesheets/api/v1/products/search.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
沒有用到的檔案可以砍掉

2022-05-21 06:17 UTC, ChenKLi commented on app/controllers/products_controller.rb
> +              select: [:name])
autocomplete 的方法是不是重複寫了兩次

2022-05-21 06:17 UTC, ChenKLi commented on app/controllers/products_controller.rb
> +              select: [:name])
autocomplete 的方法是不是重複寫了兩次

2022-05-21 06:17 UTC, ChenKLi commented on app/javascript/controllers/autocomplete_controller.js
> +import { Application } from '@hotwired/stimulus'
印象中我們已經把 @hotwired/stimulus 給拿掉了，所以沒有這個東西可以引入

2022-05-21 06:17 UTC, ChenKLi commented on app/javascript/controllers/autocomplete_controller.js
> +import { Application } from '@hotwired/stimulus'
印象中我們已經把 @hotwired/stimulus 給拿掉了，所以沒有這個東西可以引入

2022-05-21 06:17 UTC, ChenKLi commented on app/javascript/controllers/index.js
> +
這兩段可以跟上面稍微整理一下，應該可以不用獨立在下面兩行寫

2022-05-21 06:17 UTC, ChenKLi commented on app/javascript/controllers/index.js
> +
這兩段可以跟上面稍微整理一下，應該可以不用獨立在下面兩行寫

2022-05-21 10:42 UTC, yamap19950521 commented on app/assets/stylesheets/api/v1/products.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
好的，我全部修正完在push上來

2022-05-22 08:19 UTC, ChenKLi approved these changes

2022-05-22 08:37 UTC, zoechaoweiting approved these changes

2022-05-22 08:37 UTC, zzr1226sdo approved these changes

2022-05-22 08:37 UTC, Weian0328 approved these changes

2022-05-22 08:37 UTC, cin-yi-wei approved these changes

2022-05-22 09:51 UTC, merged